import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SRC = path.join(__dirname, "tokens.json");
const DIST = path.join(__dirname, "..", "dist");

type ColorLeaf = { light: string; dark: string };
type ValueLeaf = { value: string };
type Leaf = ColorLeaf | ValueLeaf;

type Tree = Record<string, unknown>;

const raw = JSON.parse(await fs.readFile(SRC, "utf-8")) as Tree;

/** Semantic color names → dot path under color.* */
const COLOR_PATH_MAP: Record<string, string> = {
  BACKGROUND: "color.background.default",
  BACKGROUND_ALT: "color.background.alt",
  SURFACE: "color.surface.default",
  SURFACE_ALT: "color.surface.alt",
  SURFACE_MUTED: "color.surface.muted",
  BORDER: "color.border.default",
  PRIMARY: "color.brand.primary",
  PRIMARY_DARK: "color.brand.primaryDark",
  PRIMARY_LIGHT: "color.brand.primaryLight",
  GREEN: "color.brand.green",
  GREEN_LIGHT: "color.brand.greenLight",
  GREEN_TEXT: "color.brand.greenText",
  PURPLE: "color.brand.purple",
  TEXT_INK: "color.text.ink",
  TEXT_BODY: "color.text.body",
  TEXT_MUTED: "color.text.muted",
  CUISINE_TAIWANESE: "color.cuisine.taiwanese",
  CUISINE_THAI: "color.cuisine.thai",
  CUISINE_JAPANESE: "color.cuisine.japanese",
  CUISINE_EUROPEAN: "color.cuisine.european",
  CUISINE_KIDS: "color.cuisine.kids",
};

function isColorLeaf(node: unknown): node is ColorLeaf {
  return (
    typeof node === "object" &&
    node !== null &&
    "light" in node &&
    "dark" in node &&
    typeof (node as ColorLeaf).light === "string"
  );
}

function isValueLeaf(node: unknown): node is ValueLeaf {
  return typeof node === "object" && node !== null && "value" in node;
}

function unwrapDtcg(node: unknown): unknown {
  if (
    typeof node === "object" &&
    node !== null &&
    "$value" in node &&
    (node as { $value?: unknown }).$value !== undefined
  ) {
    return (node as { $value: unknown }).$value;
  }
  return node;
}

function flattenCss(
  tree: Tree,
  prefix: string[] = [],
): Array<{ name: string; light: string; dark?: string }> {
  const out: Array<{ name: string; light: string; dark?: string }> = [];
  for (const [key, value] of Object.entries(tree)) {
    if (key.startsWith("$") || key === "meta") continue;
    const pathParts = [...prefix, key];
    const unwrapped = unwrapDtcg(value);
    if (isColorLeaf(unwrapped)) {
      out.push({
        name: pathParts.join("-"),
        light: unwrapped.light,
        dark: unwrapped.dark,
      });
    } else if (isValueLeaf(unwrapped)) {
      out.push({ name: pathParts.join("-"), light: unwrapped.value });
    } else if (typeof value === "object" && value !== null) {
      out.push(...flattenCss(value as Tree, pathParts));
    }
  }
  return out;
}

const cssVars = flattenCss(raw);
const lightLines = cssVars.map((v) => `  --${v.name}: ${v.light};`);
const darkLines = cssVars
  .filter((v) => v.dark !== undefined)
  .map((v) => `  --${v.name}: ${v.dark};`);

const css = `/* Auto-generated by @chef/design-tokens. Do not edit by hand. */
:root {
  color-scheme: light;
${lightLines.join("\n")}
}

/* OS dark mode applies only when the user has not explicitly chosen light. */
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    color-scheme: dark;
${darkLines.join("\n")}
  }
}

[data-theme="dark"] {
  color-scheme: dark;
${darkLines.join("\n")}
}

/* Web shorthand aliases (globals.css) */
:root {
  --bg: var(--color-background-default);
  --surface: var(--color-surface-default);
  --border: var(--color-border-default);
  --primary: var(--color-brand-primary);
  --primary-dark: var(--color-brand-primaryDark);
  --green: var(--color-brand-green);
  --text-ink: var(--color-text-ink);
  --text-body: var(--color-text-body);
  --text-muted: var(--color-text-muted);
}
`;

const tailwindColors: Record<string, string> = {};
for (const [k, dot] of Object.entries(COLOR_PATH_MAP)) {
  const short = dot.replace(/^color\./, "").replace(/\./g, "-");
  tailwindColors[short] = `var(--${dot.replace(/\./g, "-")})`;
}

const colorEntries = Object.entries(tailwindColors)
  .map(([k, v]) => `        "${k}": "${v}"`)
  .join(",\n");

const tailwindPreset = `/** Auto-generated by @chef/design-tokens */
const preset = {
  theme: {
    extend: {
      colors: {
${colorEntries}
      },
      borderRadius: {
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
      },
    },
  },
};

export default preset;
`;

const indexTs = `// Auto-generated entry — import tokens.json for tooling.
import tokens from "../src/tokens.json" with { type: "json" };
export { tokens };
export type Tokens = typeof tokens;
`;

await fs.mkdir(DIST, { recursive: true });
await fs.writeFile(path.join(DIST, "tokens.css"), css);
await fs.writeFile(path.join(DIST, "tailwind-preset.js"), tailwindPreset);
await fs.writeFile(path.join(DIST, "index.ts"), indexTs);
console.log("Generated", Object.keys(COLOR_PATH_MAP).length, "color tokens");
