"""LINE Flex design tokens for the Dark Michelin theme."""

from __future__ import annotations

# Core palette
PRIMARY_BG = "#1A1C1E"
SURFACE_BG = "#2A2D30"
SECONDARY_TEXT = "#706A5F"
ACCENT_ORANGE = "#EA580C"
NEUTRAL_TEXT = "#F7F3EB"
SURFACE_ALT = "#34383C"
SURFACE_MUTED = "#232629"

# 三廚角色標籤色
ROLE_COLORS: dict[str, str] = {
    "行政主廚": "#C97845",
    "副主廚": "#8A7F6C",
    "食材總管": "#B08D57",
}

# 文字階層
TEXT_INK = NEUTRAL_TEXT
TEXT_BODY = NEUTRAL_TEXT
TEXT_MUTED = SECONDARY_TEXT
TEXT_STRONG = NEUTRAL_TEXT

# 無主圖時文字 hero
HERO_BLOCK_BG = PRIMARY_BG
HERO_KICKER = ACCENT_ORANGE
HERO_SUB = SECONDARY_TEXT
HERO_TITLE = NEUTRAL_TEXT

# 主選單
MENU_HEADER_BG = PRIMARY_BG
MENU_HEADER_TEXT = NEUTRAL_TEXT
MENU_BODY_BG = SURFACE_BG
MENU_BTN_CUISINE = ACCENT_ORANGE
MENU_BTN_FRIDGE = ACCENT_ORANGE
MENU_BTN_BUDGET = ACCENT_ORANGE
MENU_BTN_MOOD = ACCENT_ORANGE
MENU_BTN_SECONDARY = SECONDARY_TEXT
MENU_BTN_TERTIARY = SECONDARY_TEXT

# 菜系輪播（保留辨識度，但壓低飽和度以貼合暗色主題）
CUISINE_HERO_TAIWANESE = "#5A3329"
CUISINE_HERO_THAI = "#31473A"
CUISINE_HERO_JAPANESE = "#4A3340"
CUISINE_HERO_EU = "#33424A"
CUISINE_HERO_KIDS = "#57482E"

CUISINE_HERO_LABEL = SECONDARY_TEXT
CUISINE_HERO_TITLE = NEUTRAL_TEXT
CUISINE_BODY_TITLE = TEXT_INK
CUISINE_BODY_DESC = TEXT_MUTED
CUISINE_FOOTER_BTN = ACCENT_ORANGE

# 食譜主卡
SURFACE_CARD = SURFACE_BG
ACCENT_TOP_STRIP = ACCENT_ORANGE
THEME_LABEL = SECONDARY_TEXT
TITLE_PRIMARY = TEXT_INK
TALK_CONTENT = TEXT_INK

PANEL_CONFERENCE_BG = SURFACE_ALT
PANEL_CONFERENCE_LABEL = SECONDARY_TEXT

SECTION_LABEL = SECONDARY_TEXT
SHOP_BULLET = TEXT_BODY

ING_NAME = TEXT_BODY
ING_PRICE = TEXT_INK

PANEL_COST_OUTER_BG = SURFACE_ALT
PANEL_COST_BORDER = SECONDARY_TEXT
SEP_COLOR = SECONDARY_TEXT
TOTAL_BAND_BG = SURFACE_MUTED
TOTAL_LABEL = SECONDARY_TEXT

STEP_NUM = ACCENT_ORANGE
MORE_STEPS_HINT = SECONDARY_TEXT

FOOTER_BTN_SECONDARY = SECONDARY_TEXT
FOOTER_BTN_FAVORITE = ACCENT_ORANGE
FOOTER_DISCLAIMER = SECONDARY_TEXT

VIDEO_BTN = ACCENT_ORANGE
EXPAND_BTN_BG = SECONDARY_TEXT

ROLE_FALLBACK = TEXT_MUTED

# 收藏輪播
FAV_THEME_LABEL = THEME_LABEL
FAV_TITLE = TITLE_PRIMARY
FAV_ING = TEXT_MUTED
FAV_COST_LABEL = SECONDARY_TEXT
FAV_REDO_BTN = ACCENT_ORANGE

# Fallback / 截斷提示
FALLBACK_STRIP = ACCENT_ORANGE
FALLBACK_TITLE = TEXT_INK
FALLBACK_HINT = SECONDARY_TEXT
FALLBACK_BODY = TEXT_INK
